2021-08-19 14:37:15,295 INFO    MainThread:45900 [internal.py:wandb_internal():91] W&B internal server running at pid: 45900, started at: 2021-08-19 14:37:13.706511
2021-08-19 14:37:15,298 DEBUG   HandlerThread:45900 [handler.py:handle_request():94] handle_request: run_start
2021-08-19 14:37:15,298 INFO    WriterThread:45900 [datastore.py:open_for_write():77] open: /tmldata1/saberika/advex-uar/advex_uar/wandb/offline-run-20210819_143636-2zcrmxe8/run-2zcrmxe8.wandb
2021-08-19 14:37:18,216 DEBUG   HandlerThread:45900 [meta.py:__init__():34] meta init
2021-08-19 14:37:18,216 DEBUG   HandlerThread:45900 [meta.py:__init__():48] meta init done
2021-08-19 14:37:18,217 DEBUG   HandlerThread:45900 [meta.py:probe():190] probe
2021-08-19 14:37:19,589 DEBUG   HandlerThread:45900 [meta.py:_setup_git():180] setup git
2021-08-19 14:37:32,901 DEBUG   HandlerThread:45900 [meta.py:_setup_git():187] setup git done
2021-08-19 14:37:33,607 DEBUG   HandlerThread:45900 [meta.py:_save_pip():52] save pip
2021-08-19 14:37:35,630 DEBUG   HandlerThread:45900 [meta.py:_save_pip():66] save pip done
2021-08-19 14:37:35,630 DEBUG   HandlerThread:45900 [meta.py:probe():231] probe done
2021-08-19 14:47:42,455 WARNING MainThread:45900 [internal.py:wandb_internal():146] Internal process interrupt: 1
2021-08-19 14:47:42,837 INFO    MainThread:45900 [internal.py:handle_exit():78] Internal process exited
